-- 002_portfolio_schema.sql
-- Portfolio content tables + generic config storage.

-- Generic updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Content tables (singleton sections + lists)
create table if not exists public.hero_section (
  id int primary key default 1,
  greeting text,
  job_title text,
  welcome_title text,
  welcome_text text,
  hero_image_url text,
  hero_image_alt text,
  updated_at timestamptz not null default now(),
  constraint hero_section_singleton check (id = 1)
);

create table if not exists public.about_section (
  id int primary key default 1,
  heading text,
  tagline text,
  body text,
  image_url text,
  image_alt text,
  updated_at timestamptz not null default now(),
  constraint about_section_singleton check (id = 1)
);

create table if not exists public.social_links (
  id int generated by default as identity primary key,
  label text not null,
  href text not null,
  icon text not null,
  sort_order int not null default 1,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.showcases (
  id int generated by default as identity primary key,
  status text not null check (status in ('current','future')),
  header_title text not null,
  project_title text not null,
  description text not null,
  image_url text not null,
  image_alt text not null,
  image_title text,
  tags jsonb not null default '[]'::jsonb,
  sort_order int not null default 1,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.skill_categories (
  id int generated by default as identity primary key,
  title text not null,
  sort_order int not null default 1,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.skill_items (
  id int generated by default as identity primary key,
  category_id int not null references public.skill_categories(id) on delete cascade,
  label text not null,
  icon_key text not null,
  sort_order int not null default 1,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

-- Generic config store (future-proof for multi-app / multi-namespace)
create table if not exists public.app_configs (
  app text not null,
  namespace text not null,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (app, namespace)
);

-- Triggers for updated_at
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'trg_hero_section_updated_at') then
    create trigger trg_hero_section_updated_at
    before update on public.hero_section
    for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_about_section_updated_at') then
    create trigger trg_about_section_updated_at
    before update on public.about_section
    for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_social_links_updated_at') then
    create trigger trg_social_links_updated_at
    before update on public.social_links
    for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_showcases_updated_at') then
    create trigger trg_showcases_updated_at
    before update on public.showcases
    for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_skill_categories_updated_at') then
    create trigger trg_skill_categories_updated_at
    before update on public.skill_categories
    for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_skill_items_updated_at') then
    create trigger trg_skill_items_updated_at
    before update on public.skill_items
    for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_app_configs_updated_at') then
    create trigger trg_app_configs_updated_at
    before update on public.app_configs
    for each row execute function public.set_updated_at();
  end if;
end $$;

-- RLS -----------------------------------------------------------------------
alter table public.hero_section enable row level security;
alter table public.about_section enable row level security;
alter table public.social_links enable row level security;
alter table public.showcases enable row level security;
alter table public.skill_categories enable row level security;
alter table public.skill_items enable row level security;
alter table public.app_configs enable row level security;

-- Public read (portfolio is a public website)
create policy "hero_section: public read" on public.hero_section for select using (true);
create policy "about_section: public read" on public.about_section for select using (true);
create policy "social_links: public read" on public.social_links for select using (true);
create policy "showcases: public read" on public.showcases for select using (true);
create policy "skill_categories: public read" on public.skill_categories for select using (true);
create policy "skill_items: public read" on public.skill_items for select using (true);
create policy "app_configs: public read portfolio" on public.app_configs
for select
using (app = 'portfolio');

-- Admin write (and admin read via FOR ALL)
create policy "hero_section: admin write" on public.hero_section
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "about_section: admin write" on public.about_section
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "social_links: admin write" on public.social_links
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "showcases: admin write" on public.showcases
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "skill_categories: admin write" on public.skill_categories
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "skill_items: admin write" on public.skill_items
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "app_configs: admin write" on public.app_configs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

